---
title: "Untitled"
author: "Michael Rose"
date: "January 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(forcats)
```

```{r}
# var that records month
x1 <- c("Dec", "Apr", "Jan", "Mar")
x2 <- c("Dec", "Apr", "Jam", "Mar")

# doesn't sort in any useful way
sort(x1)


# create a list of valid levels
month_levels <- c(
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
)

# create a factor
y1 <- factor(x1, levels = month_levels)
y1

# sort works now
sort(y1)

# any values not in the set will be silently converted to NA
y2 <- factor(x2, levels = month_levels)
y2

# to find errors
y2 <- parse_factor(x2, levels = month_levels)

# if levels are omitted, they will be taken in alphabetical order
factor(x1)

# make the levels match the order of the first appearance in the data
f1 <- factor(x1, levels = unique(x1))
f1

# or, after the fact, with fct_inorder
f2 <- x1 %>% factor() %>% fct_inorder()
f2

# access the set of valid levels directly
levels(f2)
```

### General Social Survey

```{r}

gss_cat

# When factors are stored in a tibble, its hard to see their levels
gss_cat %>% count(race)

ggplot(gss_cat, aes(race)) +
  geom_bar() + 
  scale_x_discrete(drop = FALSE) # show levels without any values
```

```{r}

# explore the distribution of rincome (reported income). What makes the default bar chart hard to understand? How could you improve the plot? 

ggplot(gss_cat, aes(rincome)) + 
  geom_bar() + 
  theme(axis.text.x = element_text(angle = 90)) +  # change text angle
  coord_flip()

# What is the most common relig in this survey? What's the most common partyid? 

ggplot(gss_cat, aes(relig)) + 
  geom_bar() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  coord_flip()

gss_cat %>% 
  count(relig) %>% 
  arrange(-n) %>% 
  head(3)

gss_cat %>% 
  count(partyid) %>% 
  arrange(-n) %>% 
  head(3)

# What relig does denom(denomination) apply to? How can you find out with a table? How can you find out with a visualization? 

levels(gss_cat$denom)

# filter 

gss_cat %>% 
  filter(!denom %in% c("No Answer", "Other", "Don't know", "Not applicable", "No denomination")) %>% 
  count(relig)
  
```

### Modifying Factor Order

```{r}
  relig <- gss_cat %>% 
    group_by(relig) %>% 
    summarize(
      age = mean(age, na.rm = TRUE),
      tvhours = mean(tvhours, na.rm = TRUE),
      n = n()
    )

ggplot(relig, aes(tvhours, relig)) + geom_point()

# fct_reorder reorders the factors. Parameters: f is the factor whose levels you want to modify, x is a numeric vector than you want to use to reorder the levels, fun is a function thats used if there are multiple values of x for each value of f. The default value is median

ggplot(relig, aes(tvhours, fct_reorder(relig, tvhours))) + 
  geom_point()

# the previous plot can be rewritten with mutate as

relig %>% 
  mutate(relig = fct_reorder(relig, tvhours)) %>% 
  ggplot(aes(tvhours, relig)) + 
  geom_point()

# Average age vs price level

rincome <- gss_cat %>% 
  group_by(rincome) %>% 
  summarize(
    age = mean(age, na.rm = TRUE),
    tvhours = mean(tvhours, na.rm = TRUE),
    n = n()
  )

# the order gets all messed up because we reordered the already ordered factors
ggplot(rincome, aes(age, fct_reorder(rincome, age))) + geom_point()

# fct_relevel taks a factor, f, and then any number of levels that you want to move to the front of the line

ggplot(rincome, aes(age, fct_relevel(rincome, "Not applicable"))) + 
  geom_point()

# when using line colors on a plot, fct_reorder2 reorders the factor by the y values associated with the largest x values.

by_age <- gss_cat %>%
  filter(!is.na(age)) %>%
  group_by(age, marital) %>%
  count() %>%
  mutate(prop = n / sum(n))

ggplot(by_age, aes(age, prop, colour = marital)) +
  geom_line(na.rm = TRUE)

ggplot(by_age, aes(age, prop, colour = fct_reorder2(marital, age, prop))) +
  geom_line() +
  labs(colour = "marital")

# for barplots, you can use fct_infreq() to order levels in increasing frequency. 

gss_cat %>% 
  mutate(marital = marital %>%  fct_infreq() %>% fct_rev()) %>% 
  ggplot(aes(marital)) + 
  geom_bar()



```

```{r}

# There are some suspiciously high numbers in tvhours. Is the mean a good summary ?

summary(gss_cat[["tvhours"]])

gss_cat %>% 
  filter(!is.na(tvhours)) %>% 
  ggplot(aes(x = tvhours)) + 
  geom_histogram(binwidth = 1)

# mean seems good, but it could be artifically inflated due to the outliers at 20 and 24

# for each factor in gss_cat identify whether the order of the levels is arbitrary or principled

# keep prints out the names of only the factors
keep(gss_cat, is.factor) %>% names()

# marital

levels(gss_cat[["marital"]])

gss_cat %>% 
  ggplot(aes(x = marital)) + 
  geom_bar()

# race

levels(gss_cat$race)

gss_cat %>% 
  ggplot(aes(race)) + 
  geom_bar()

# rincome

levels(gss_cat$rincome)

# relig

levels (gss_cat[["relig"]])

gss_cat %>% 
  ggplot(aes(relig)) + 
  geom_bar() + 
  coord_flip()

# denom

levels(gss_cat$denom)

# partyid

levels(gss_cat[["partyid"]])

```

### Modifying Factor Levels 

```{r}

# our levels are terse and inconsistent
gss_cat %>% 
  count(partyid)

# tweak names
gss_cat %>% 
  mutate(partyid = fct_recode(partyid,
        "Republican, strong" = "Strong Republican",
        "Republican, weak"   = "Not Strong Republican",
        "Independent, near rep" = "Ind, near rep", 
        "Independent, near dem" = "Ind, near dem", 
        "Democrat, weak"     = "Not Strong Democrat",
        "Democrat, strong"   = "Strong Democrat"
                              )) %>% 
  count(partyid)

# to combine groups
gss_cat %>% 
  mutate(partyid = fct_recode(partyid,
        "Republican, strong" = "Strong Republican",
        "Republican, weak"   = "Not Strong Republican",
        "Independent, near rep" = "Ind, near rep", 
        "Independent, near dem" = "Ind, near dem", 
        "Democrat, weak"     = "Not Strong Democrat",
        "Democrat, strong"   = "Strong Democrat",
        "Other"              = "No answer",
        "Other"              = "Don't know",
        "Other"              = "Other party"
                              )) %>% 
  count(partyid)

# fct_collapse 

gss_cat %>% 
  mutate(partyid = fct_collapse(partyid,
        other = c("No answer", "Don't know", "Other party"),
        rep = c("Strong republican", "Not str republican"),
        ind = c("Ind,near rep", "Independent", "Ind,near dem"),
        dem = c("Not str democrat", "Strong democrat")
                                )) %>% 
  count(partyid)

# fct_lump lumps all the small groups together

# default is to aggregate so that way the combined smaller groups are smaller than the larger group
gss_cat %>% 
  mutate(relig = fct_lump(relig)) %>% 
  count(relig)

# n parameter

gss_cat %>% 
  mutate(relig = fct_lump(relig, n = 10)) %>% 
  count(relig, sort = TRUE) %>% 
  print(n = Inf)

```

```{r}
# How have the proportions of people identifying as democrat, republican, and independent changed over time ?

levels(gss_cat$partyid)

# combine levels

gss_cat %>% 
  mutate(partyid = fct_collapse(partyid,
        other = c("No answer", "Don't know", "Other party"),
        rep = c("Strong republican", "Not str republican"),
        ind = c("Ind,near rep", "Independent", "Ind,near dem"),
        dem = c("Not str democrat", "Strong democrat")
        )) %>% 
  count(year, partyid) %>% 
  group_by(year, partyid) %>% 
  mutate(prop = n / sum(n)) %>% 
  ggplot(aes(x = year, y = prop,
             color = fct_reorder2(partyid, year, prop))) + 
  geom_point() + geom_line() + labs(color ="Party ID")

# How could you collapse rincome into a small set of categories? 

levels(gss_cat$rincome)

library("stringr")

gss_cat %>% 
  mutate(rincome = fct_collapse(rincome,
    "Unknown" = c("No answer", "Don't know", "Refused", "Not applicable"),
    "Lt $5000" = c("Lt $1000", str_c("$", c("1000", "3000", "4000"), " to ", c("2999", "3999", "4999"))),
    "$5000 to $10000" = str_c("$", c("5000", "6000", "7000", "8000"), " to ", c("5999", "6999", "7999", "8999"))
  )) %>% 
  ggplot(aes(x = rincome)) + 
  geom_bar() + 
  coord_flip()

```


