---
title: 'Chapter 21: Graphics for Communication'
author: "Michael Rose"
date: "April 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(modelr)
library(lubridate)
```

## Label

```{r}
# Use a title that summarizes the main finding

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth(se = FALSE) + 
  labs(title = paste(
    "Fuel Efficiency generally decreases with engine size"
  ),
  subtitle = paste(
    "Two seaters (sports cars) are an exception because of their light weight"
  ),
  caption = "Data from fueleconomy.gov")

# It is possible to use mathematical equations rather than text. 
# switch out "" for quote() and to see available options check out ?plotmath
df <- tibble(
  x = runif(10),
  y = runif(10)
)

ggplot(df, aes(x, y)) + 
  geom_point() + 
  labs(
    x = quote(sum(x[i]^2, i == 1, n)),
    y = quote(alpha + beta + frac(delta, theta))
  )

```

```{r}
# Create one plot on the fuel economy data with customized title, subtitle, caption, x,y, and color labels

ggplot(mpg, aes(fct_reorder(mpg$manufacturer, mpg$hwy), mpg$hwy)) + 
  geom_point(aes(color = mpg$class)) + 
  geom_smooth(se = FALSE) + 
  labs(
    x = "Manufacturer",
    y = "Highway Miles per Gallon",
    title = "Foreign Cars tend to have high gas mileage",
    subtitle = "Toyota particularly has the most variance in mpg",
    color = "Car Type",
    caption = "Data from fueleconomy.gov"
  ) + 
  theme(
    axis.text.x = element_text(angle = 90)
  )

ggplot(data = mpg, mapping = aes(x = reorder(class, hwy, median), y = hwy)) + 
  geom_boxplot() + 
  coord_flip() + 
  labs(
    title = "Compact Cars have > 10 Highway mpg than Pickup Trucks",
    subtitle = "Comparing the median highway mpg in each class", 
    caption = "Data from fueleconomy.gov",
    x = "Car Class",
    y = "Highway Miles per Gallon"
  )


unique(mpg$class)

mpg_no2seater <- mpg %>% 
  filter(!.$class == "2seater") 

mpg_no2seater %>% 
ggplot(aes(displ, hwy)) +
  geom_point(aes(color = mpg_no2seater$class)) + 
  geom_smooth(se = FALSE)

ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point(aes(colour = class)) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Fuel efficiency generally decreases with engine size",
    subtitle = "Subcompact cars show the greatest sensitivity to engine size",
    caption = "Data from fueleconomy.gov"
  )
  
mod <- lm(hwy ~ class, data = mpg)
mpg %>% 
  add_residuals(mod) %>% 
  ggplot(aes(displ, resid)) + 
  geom_point() + 
  geom_smooth(method= "lm", se = FALSE) + 
  labs(
    title = "Fuel efficiency decreases with engine size",
    subtitle = "Highway MPG for cars after subtracting mean mpg of their class",
    x = "Highway MPG relative to Class",
    y = "Engine Displacement"
  )

```

## Annotations 

```{r}
best_in_class <- mpg %>% 
  group_by(class) %>% 
  filter(row_number(desc(hwy)) == 1)

best_in_class %>% head()

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_text(aes(label = model), data = best_in_class)

# geom_label draws a rectangle behind the text

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_label(
    aes(label = model),
    data = best_in_class,
    nudge_y = 2,
    alpha = 0.5
  )

# use ggrepel to fix overlapping labels

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_point(size = 3, shape = 1, data = best_in_class) + 
  ggrepel::geom_label_repel(
    aes(label = model), 
    data = best_in_class
  )


# show averages on plot

class_avg <- mpg %>% 
  group_by(class) %>% 
  summarize(
    displ = median(displ),
    hwy = median(hwy)
  )

ggplot(mpg, aes(displ, hwy, color = class)) + 
  ggrepel::geom_label_repel(aes(label = class),
                            data = class_avg, 
                            size = 6,
                            label.size = 0,
                            segment.color = NA) + 
  geom_point() + 
  theme(legend.position = "none")


# add a single label

label <- mpg %>% 
  summarize(
    displ = max(displ),
    hwy = max(hwy),
    label = paste(
      "Increasing engine size is\nrelated to decreasing fuel economy"
    )
  )

ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  geom_text(
    aes(label = label),
    data = label, 
    vjust = "top",
    hjust = "right"
  )

# if you want the text exactly on the border of the plot, use +-inf

label <- tibble(
  displ = Inf,
  hwy = Inf,
  label = paste(
    "Increasing engine size\nrelated to decreasing fuel economy"
  )
)

ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  geom_text(
    aes(label = label),
    data = label, 
    vjust = "top",
    hjust = "right"
  )

# instead of manually breaking lines with \n we can use stringr::str_wrap
"increasing engine size related to decreasing fuel economy" %>% 
  stringr::str_wrap(width = 40) %>% 
  writeLines()

# geom_hline and geom_vline add reference lines
# geom_rect adds a rectangle around points of interest 
# geom_segment draws attention to a point with an arrow 

```

```{r}

label <- tribble(
    ~displ, ~hwy, ~label, ~vjust, ~hjust,
     Inf,  Inf,    "Top right", "top", "right",
     Inf, -Inf,    "Bottom right", "bottom", "right",
    -Inf,  Inf,    "Top left", "top", "left",
    -Inf, -Inf,    "Bottom left", "bottom", "left"
)

# Use geom_text with infinite positions to place text at the four corners of the plot 
ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_text(
    aes(label = label, vjust = vjust, hjust = hjust), 
    data = label
  )

# Read the documentation for annotate(). How can you use it to add a text label to a plot without having to create a tibble? 

# annotate adds geoms to the plot, but instead of mapping the variables from a dataframe it passes them in as vectors. This is usefil for adding small annotations such as text labels or if you have your data in vectors and don't want to put them into a dataframe. We can use it to add a text label to a plot by creating a vector of length 1 of the string and then using annotate to pass it in as a geom's data. 

ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  annotate("text", x = Inf, y = Inf, 
           label = "Increasing engine size is \n related to decreasing fuel economy", vjust = "top", hjust = "right")

# How do labels with a geom_text() interact with facetting? How can you add a label to a single facet? How can you put a different label in each facet? (Hint: Think about the underlying data)

# if the facet variable is not specified, the text is drawn in all facets

label <- tibble(
  displ = Inf, 
  hwy = Inf, 
  label = "Increasing engine size is \n related to decreasing fuel economy"
)

ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  geom_text(aes(label = label), data = label, vjust = "top", hjust = "right", size = 2) + 
  facet_wrap(~class)

# To draw the label in only one facet, add a column to the label data frame with the value of faceting variables in which to draw it 

label <- tibble(
  displ = Inf, 
  hwy = Inf,
  class = "2seater",
  label = "Increasing engine size is \n related to decreasing fuel economy"
)

ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  geom_text(aes(label = label), 
            data = label, 
            vjust = "top",
            hjust = "right",
            size = 2) + 
  facet_wrap(~class)

# To draw labels in different plots, simply have the facetting variable(s)

label <- tibble(
  displ = Inf, 
  hwy = Inf, 
  class = unique(mpg$class),
  label = stringr::str_c("Label for ", class)
)

ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  geom_text(aes(label = label),
            data = label, 
            vjust = "top",
            hjust = "right",
            size = 3) + 
  facet_wrap(~class)

# What arguments to geom_label() control the appearance of the background box? 

# label.padding, label.r, label.size, alpha, color

# What are the four arguments to arrow()? How do they work? Create a series of plots that demonstrate the most important options

# angle, length, ends, type (open or close: open or closed triangle head)

```

## Scales

When you do 

```{r}
ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class))

# ggplot automatically does the following 

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  scale_x_continuous() + 
  scale_y_continuous() + 
  scale_color_discrete()
```

### Axis Ticks and Legend Keys

```{r}
# breaks control the position of the ticks or the values associated with the keys 
# labels control the text label associated with each tick/key

ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  scale_y_continuous(breaks = seq(15, 40, by = 5))

# Suppress the ticks

ggplot(mpg, aes(displ, hwy)) +
  geom_point() + 
  scale_x_continuous(labels = NULL) + 
  scale_y_continuous(labels = NULL)

# another use of breaks is when you have relatively few data points and want to show where the observations occur

presidential %>% 
  mutate(id = 33 + row_number()) %>% 
  ggplot(aes(start, id)) + 
  geom_point() + 
  geom_segment(aes(xend = end, yend = id)) + 
  scale_x_date(
    NULL,
    breaks = presidential$start, # set axis points to years presidents start
    date_labels = "'%y" # a date specifier, e.g. 'year
  )

```

### Legend Layout

```{r}
base <- ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class))

base + theme(legend.position = "left")
base + theme(legend.position = "top")
base + theme(legend.position = "right")
base + theme(legend.position = "bottom")

# control the display of the legend

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom") + 
  guides(
    color = guide_legend(
      nrow = 1, # keep legend to one row
      override.aes = list(size = 4) # change size of dots
    )
  )

```

## Replacing a scale

```{r}
# plot transformations
ggplot(diamonds, aes(carat, price)) + 
  geom_bin2d()

# gross. Now lets transform

ggplot(diamonds, aes(log10(carat), log10(price))) + 
  geom_bin2d()

# this is linear, but now the scales are hard to interpret. We can change just the scale rather than interpreting the variables 

ggplot(diamonds, aes(carat, price)) + 
  geom_bin2d() + 
  scale_x_log10() + 
  scale_y_log10()

# We can also change the color scale

# colorbrewer is designed to be interpretable by people with color blindness

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = drv))

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = drv)) + 
  scale_color_brewer(palette = "Set1")

# if there are just a few colors, we can add a shape mapping

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = drv, shape = drv)) + 
  scale_color_brewer(palette = "Set1")

# When you have a predefined mapping between values, use scale_color_manual

presidential %>% 
  mutate(id = 33 + row_number()) %>% 
  ggplot(aes(start, id, color = party)) + 
  geom_point() + 
  geom_segment(aes(xend = end, yend = id)) + 
  scale_color_manual(
    values = c(Republican = "red", Democratic = "blue")
  )

# for continous, we can use scale_color_gradient() or scale_fill_gradient()

# viridis

df <- tibble(
  x = rnorm(10000),
  y = rnorm(10000)
)

# regular (still looks nice)
ggplot(df, aes(x, y)) + 
  geom_hex() + 
  coord_fixed()

# viridis (changed gradient palette)
ggplot(df, aes(x,y)) + 
  geom_hex() + 
  viridis::scale_fill_viridis() + 
  coord_fixed()
```

```{r}
# why doesn't the following code override the default scale? 
ggplot(df, aes(x,y)) + 
  geom_hex() + 
  scale_color_gradient(low = "white", high = "red") + 
  coord_fixed()

# the colors in geom_hex are set by fill and not color
ggplot(df, aes(x,y)) + 
  geom_hex() + 
  scale_fill_gradient(low = "white", high = "red") + 
  coord_fixed()

# What is the first argument to every scale? How does it compare to labs? 
# the first argument is the label, which is equivalent to labs

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth(se = FALSE) + 
  labs(
    x = "Engine Displacement (L)",
    y = "Highway Fuel Economy (mpg)",
    color = "Car Type"
  )

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth(se = FALSE) + 
  scale_x_continuous("Engine Displacement (L)") + 
  scale_y_continuous("Highway Fuel Economy (mpg)") +
  scale_color_discrete("Car Type")

# Change the display of the presidential terms by 
# a. combining the two variants shown above
# b. Improving the display of the y axis
# c. Labeling each term with the name of the president
# d. adding informative plot labels
# e. Placing breaks every 4 years (this is trickier than it seems)

years <- lubridate::make_date(seq(year(min(presidential$start)), year(max(presidential$end)), by = 4), 1, 1)

presidential %>% 
  mutate(id = 33 + row_number(),
         name_id = stringr::str_c(name, " (", id, ")"),
         name_id = factor(name_id, levels = name_id)) %>%
  ggplot(aes(start, name_id, color = party)) + 
  geom_point() + 
  geom_segment(aes(xend = end, yend = name_id)) + 
  scale_color_manual(values = c(Republican = "red", Democratic = "blue")) + 
  scale_y_discrete(NULL) + 
  scale_x_date(NULL, breaks = years, date_labels = "'%y") + 
  theme(panel.grid.minor = element_blank())
  
# Use override.aes to make the legend on the following plot easier to see:
ggplot(diamonds, aes(carat, price)) + 
  geom_point(aes(color = cut), alpha = 1/20) + 
  theme(legend.position = "bottom") + 
  guides(
    color = guide_legend(
      override.aes = list(size = 4, alpha = 1) # change size of dots
    )
  )

```

## Zooming

There are three ways to control the plot limits: 

* Adjusting what data is plotted
* Setting the limits in each scale
* setting xlim and ylim in coord_cartesian()


```{r}
# to zoom in on a region of the plot, its best to use coord_cartesian
# compare: 
ggplot(mpg, mapping = aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth() + 
  coord_cartesian(xlim = c(5,7), ylim = c(10,30))

mpg %>% 
  filter(displ >= 5, displ <= 7, hwy >= 10, hwy <= 30) %>% 
  ggplot(aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth()

# it is difficult to change the scales if we want to seperate certain factors because they all have individual scales with different ranges. e.g.:
suv <- mpg %>% filter(class == "suv")
compact <- mpg %>% filter(class == "compact")

ggplot(suv, aes(displ, hwy, color = drv)) + 
  geom_point()

ggplot(compact, aes(displ, hwy, color = drv)) + 
  geom_point()

# one way to overcome this problem is to share scales across multiple plots, training the scales with the limits of the full data
x_scale <- scale_x_continuous(limits = range(mpg$displ))
y_scale <- scale_y_continuous(limits = range(mpg$hwy))
col_scale <- scale_color_discrete(limits = unique(mpg$drv))

ggplot(suv, aes(displ, hwy, color = drv)) + 
  geom_point() + 
  x_scale + y_scale + col_scale

ggplot(compact, aes(displ, hwy, color = drv)) + 
  geom_point() + 
  x_scale + y_scale + col_scale

```

## Themes

```{r}
# We can customize nondata elements of our plot with a theme

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth(se = FALSE) + 
  theme_bw()

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth(se = FALSE) + 
  theme_light()

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth(se = FALSE) + 
  theme_classic()

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth(se = FALSE) + 
  theme_linedraw()

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth(se = FALSE) + 
  theme_dark()

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth(se = FALSE) + 
  theme_minimal()

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth(se = FALSE) + 
  theme_gray()

ggplot(mpg, aes(displ, hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth(se = FALSE) + 
  theme_void()

```

## Saving Your Plots

```{r}
ggplot(mpg, aes(displ, hwy)) + geom_point()
ggsave("my-plot.pdf")

```

## Figure Sizing

